"""components, client_name, resolved_at, sla policies

Revision ID: 2c98f0aab64f
Revises: d811e439cd99
Create Date: 2026-07-13 15:13:53.307688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2c98f0aab64f'
down_revision: Union[str, None] = 'd811e439cd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    # create_type=False: the 'ticketpriority' enum already exists in Postgres
    # (the tickets table created it). Letting sa.Enum re-declare it here makes
    # the migration fail with "type ticketpriority already exists".
    sa.Column('priority', postgresql.ENUM(
        'HIGHEST', 'HIGH', 'MEDIUM', 'LOW', 'LOWEST',
        name='ticketpriority', create_type=False,
    ), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('priority')
    )
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=True)
    op.add_column('tickets', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('component_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tickets_client_name'), 'tickets', ['client_name'], unique=False)
    op.create_foreign_key(None, 'tickets', 'components', ['component_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # ---- Data: reference rows the feature is useless without ----

    # Tickets that were already Done have no resolved_at, so their SLA clock
    # would keep running forever and report every closed ticket as breached.
    # updated_at is the best evidence we have of when they were closed.
    op.execute(
        "UPDATE tickets SET resolved_at = updated_at "
        "WHERE status = 'DONE' AND resolved_at IS NULL"
    )

    # Default SLA: only the top two priorities are tracked. Teams that put an
    # SLA on 'lowest' end up ignoring all of them.
    op.execute(
        "INSERT INTO sla_policies (priority, threshold_hours) VALUES "
        "('HIGHEST', 4), ('HIGH', 8), ('MEDIUM', NULL), ('LOW', NULL), ('LOWEST', NULL)"
    )

    # QTech's actual product surface, not generic Jira placeholders.
    op.execute("""
        INSERT INTO components (id, name, description, color, created_at) VALUES
        (gen_random_uuid(), 'OTRAMS-Booking',   'Booking engine and reservation flow',      '#3E7BFA', now()),
        (gen_random_uuid(), 'OTRAMS-Payments',  'Payment gateways, refunds, settlements',   '#10B981', now()),
        (gen_random_uuid(), 'OTRAMS-Reporting', 'Reports, dashboards and exports',          '#F59E0B', now()),
        (gen_random_uuid(), 'RateNet-API',      'Supplier API hub and rate aggregation',    '#8B5CF6', now()),
        (gen_random_uuid(), 'rePUSHTI',         'AI booking re-verification',               '#EC4899', now()),
        (gen_random_uuid(), 'Bizinso-Custom',   'Custom enterprise engagements',            '#06B6D4', now())
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_client_name'), table_name='tickets')
    op.drop_column('tickets', 'component_id')
    op.drop_column('tickets', 'resolved_at')
    op.drop_column('tickets', 'client_name')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_table('components')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###
