"""index handoffs by from_user + action

Revision ID: b7340a413aee
Revises: bcac3b095527
Create Date: 2026-07-14 15:28:35.325579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7340a413aee'
down_revision: Union[str, None] = 'bcac3b095527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticket_handoffs_from_action', 'ticket_handoffs', ['from_user_id', 'action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_handoffs_from_action', table_name='ticket_handoffs')
    # ### end Alembic commands ###
