"""teams and ticket handoffs

Revision ID: be7a55959112
Revises: aaed50d0b230
Create Date: 2026-07-13 17:10:54.252867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7a55959112'
down_revision: Union[str, None] = 'aaed50d0b230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('SUPPORT', 'TESTING', 'DEVELOPMENT', 'OTHER', name='teamkind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('ticket_handoffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_team_id', sa.UUID(), nullable=True),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('to_team_id', sa.UUID(), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_handoffs_sent_at'), 'ticket_handoffs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_ticket_handoffs_ticket_id'), 'ticket_handoffs', ['ticket_id'], unique=False)
    op.add_column('tickets', sa.Column('current_team_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tickets_current_team_id'), 'tickets', ['current_team_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'teams', ['current_team_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # ---- Data: the three teams the workflow needs to exist ----
    #
    # `kind` is what the state machine keys off, NOT the name — so these can be
    # renamed, and a fourth team added, without touching the routing rules.
    #
    # Deliberately assigns NOBODY to a team. Guessing which team an existing
    # user belongs to would be fabricating data; they're assigned in Settings.
    op.execute("""
        INSERT INTO teams (id, name, kind, description, color, created_at) VALUES
        (gen_random_uuid(), 'Contact/Support', 'SUPPORT',
         'Raises tickets from customer reports, and closes them once verified.', '#10B981', now()),
        (gen_random_uuid(), 'Testing/QA', 'TESTING',
         'Reproduces reported bugs, and verifies fixes.', '#F59E0B', now()),
        (gen_random_uuid(), 'Development', 'DEVELOPMENT',
         'Fixes confirmed bugs.', '#3E7BFA', now())
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_current_team_id'), table_name='tickets')
    op.drop_column('tickets', 'current_team_id')
    op.drop_index(op.f('ix_ticket_handoffs_ticket_id'), table_name='ticket_handoffs')
    op.drop_index(op.f('ix_ticket_handoffs_sent_at'), table_name='ticket_handoffs')
    op.drop_table('ticket_handoffs')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
