"""user avatar_url and theme

Revision ID: d811e439cd99
Revises: 030628bdc5bd
Create Date: 2026-07-13 15:04:28.393062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd811e439cd99'
down_revision: Union[str, None] = '030628bdc5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(), server_default='dark', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
