"""subtasks: parent_id and subtask type

Revision ID: f4b97606aabc
Revises: 2c98f0aab64f
Create Date: 2026-07-13 15:44:43.620283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b97606aabc'
down_revision: Union[str, None] = '2c98f0aab64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate does NOT detect new values added to a Postgres enum, so this
    # has to be written by hand — without it 'subtask' doesn't exist in the
    # database and every sub-task insert fails at runtime.
    #
    # ALTER TYPE ... ADD VALUE cannot run inside the transaction that then uses
    # the new value, so it goes in an autocommit block of its own.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE tickettype ADD VALUE IF NOT EXISTS 'SUBTASK'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'tickets', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres cannot remove a value from an enum, so 'SUBTASK' stays behind.
    # Harmless: nothing references it once parent_id is gone.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'parent_id')
    # ### end Alembic commands ###
